server:
  port: 8089
  servlet:
    context-path: "/cas"
cas:
  service:
    login: "${cas.url.prefix}/login"
    logout: "${cas.url.prefix}/logout"
  url:
    prefix: "http://45.77.6.219:8080/cas"
app:
  service:
    url: "http://localhost:${server.port}${server.servlet.context-path}"
    home: "http://localhost:${server.port}${server.servlet.context-path}"
mybatis:
  type-aliases-package: "com.funi.muyq.springbootangular.entity,com.funi.muyq.springbootangular.vo"
  mapper-locations: "classpath:config/mapper/*.xml"
  config-location: "classpath:config/spring/mybatis-config.xml"
spring:
  datasource:
    url: "jdbc:mysql://45.77.6.219:3306/cas?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false"
    driver-class-name: com.mysql.jdbc.Driver
    username: "root"
    password: "MYQ@hot520"
logging:
  level:
    com:
      funi:
        muyq:
          springbootangular:
            mapper: debug
